site_name: B.2 Informatik Skript
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: ["docs"]
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
extra_css:
  - styles/extra.css
nav:
  - INFI - 2 AHWII:
    - EinfÃ¼hrung: INFI/2AHWII/index.md 
    - EinfÃ¼hrung Datenbanken: INFI/2AHWII/01_why-databases.md
    - Datenbanksysteme: INFI/2AHWII/02_database-systems.md
    - Structured Query Language (SQL) - Intro:
      - EinfÃ¼hrung SQL: INFI/2AHWII/03_structured_query_language.md
      - Tabellen erstellen und lÃ¶schen: INFI/2AHWII/03_sql_create_and_drop_command.md
      - Daten einfÃ¼gen, Ã¤ndern und lÃ¶schen: INFI/2AHWII/03_sql_insert_command.md
      - Daten abfragen: INFI/2AHWII/03_sql_select_command.md
      - ðŸ§ª Erste SQL Ãœbung: INFI/2AHWII/04_exercise_movies.md
      - Tabellen Ã¤ndern: INFI/2AHWII/03_sql_alter_command.md
    - Relationen, Relationenmodelle und Datenbankentwurf:
      - EinfÃ¼hrung Relationen: INFI/2AHWII/05_relations.md
      - FremdschÃ¼ssel - Beziehungen zwischen Tabellen: INFI/2AHWII/06_foreign_keys.md
      - Tabellen verbinden: INFI/2AHWII/07_sql_join_command.md
      - ðŸ§ª Relationen Ãœbung: INFI/2AHWII/08_exercise_relations.md
      - Entity Relations (ER): INFI/2AHWII/09_entity_relations_diagram.md
  - INFI - 3 AHWII:
    - EinfÃ¼hrung: INFI/3AHWII/index.md
    - Entity Relations: INFI/3AHWII/01_entity-relations.md
  - SWP/WEB - 2 AHWII:
    - EinfÃ¼hrung in HTML: SWP/WEB/2AHWII/01_intro-web.md
    - HTML Grundstruktur und Tags: SWP/WEB/2AHWII/02_00_html-tags.md
    - Medien einbinden: SWP/WEB/2AHWII/02_01_medien.md
    - EinfÃ¼hrung in CSS: SWP/WEB/2AHWII/03_00_intro-css.md
    - Farbwerte in CSS: SWP/WEB/2AHWII/03_01_colors.md
    - Einheiten in CSS: SWP/WEB/2AHWII/03_02_units.md
    - ðŸ§ª Ãœbung - Lebenslauf: SWP/WEB/2AHWII/04_exercise_my-cv.md
    - Gruppieren von Tags: SWP/WEB/2AHWII/05_div-tag.md
    - CSS Box Modell: SWP/WEB/2AHWII/06_00_css-box-modell.md
    - Schriftgestaltung in CSS: SWP/WEB/2AHWII/06_01_css-fonts.md
    - Positionierung in CSS: SWP/WEB/2AHWII/06_02_css-positioning.md
    - Layouts in CSS: SWP/WEB/2AHWII/06_layouts-with-css.md
    - ðŸ§ª Ãœbung - Flexbox: SWP/WEB/2AHWII/07_exercise_flexbox-coding-fantasy.md
    - CSS Cheatsheet: SWP/WEB/2AHWII/08_css-cheatsheet.md
    - CSS Background: SWP/WEB/2AHWII/09_css-background.md
    - Transition und Effects: SWP/WEB/2AHWII/10_transition-and-effects.md
    - Responsive Design: SWP/WEB/2AHWII/11_responsive-design.md
    - Semantisches HTML: SWP/WEB/2AHWII/12_semantisches-html.md
    - CSS Variablen: SWP/WEB/2AHWII/13_css-variablen.md
  - FÃ¤cherÃ¼bergreifende Projekte:
    - NITFLEX - Film Verwaltung: CrossSubjectProjects/01_nitflex.md 